# API version for Service resource
# v1 is used for core Kubernetes objects like Service
apiVersion: v1

# Kind defines the Kubernetes object type
# Service provides a stable network identity for Pods
kind: Service

metadata:
  # Name of the Service
  # Used as a DNS name to access the API Gateway inside the cluster
  name: api-gateway

  # Namespace where this Service is created
  namespace: kube-credential-ns

spec:
  # Type of Service
  # ClusterIP exposes the Service only within the Kubernetes cluster
  type: ClusterIP

  # Selector connects this Service to API Gateway Pods
  # Traffic will be forwarded to Pods with label app=api-gateway
  selector:
    app: api-gateway

  ports:
    # Port configuration for the Service
    - port: 3000
      # Port exposed by the Service inside the cluster

      targetPort: 3000
      # Port on which the API Gateway container is listening
